spring:
  application:
    name: App
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 910221..a

server:
  port: 9000




